# Generated by Django 4.2.21 on 2025-10-27 09:21

import django.core.validators
from django.db import migrations, models
import profiles.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, unique=True, validators=[profiles.validators.NicknameLengthValidator()])),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Name must start with a capital letter!', regex='^[A-Z][a-zA-Z]*$')])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Name must start with a capital letter!', regex='^[A-Z][a-zA-Z]*$')])),
                ('chef', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
