# Generated by Django 4.2.21 on 2026-03-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'permissions': [('can_approve_recipes', 'Can approve recipes')]},
        ),
    ]
